function [Aircraft] = CeRAS(Aircraft)
%
% [Aircraft] = CeRAS(Aircraft)
% written by Maxfield Arnson
% last updated: 19 nov 2025
%
% nonparametric mission for a typical regional jet or narrowbody aircraft.
% intended to be used with the CeRAS aircraft model.
% see https://link.springer.com/article/10.1007/s13272-015-0177-9
%
% mission 1:          | mission 2: 1625 nmi range @ 35k ft 
% 875 nmi range       |   
% @ 33k ft            |    
%                     | _____________________________________                
%        ____________ |/                                     \
%       /             |                                       \
%      /              |                                        \
%     /               |                                         \
%    /                |                                          \
% __/                 |                                           \___
%
% INPUTS:
%     Aircraft - aircraft structure (without a mission profile).
%                size/type/units: 1-by-1 / struct / []
%
% OUTPUTS:
%     Aircraft - aircraft structure (with    a mission profile).
%                size/type/units: 1-by-1 / struct / []
%

%% IMPORT THE PERFORMANCE PARAMETERS %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

AltTko = 0;
AltCrs33 = UnitConversionPkg.ConvLength(33000, "ft", "m");
AltCrs35 = UnitConversionPkg.ConvLength(35000, "ft", "m");

VelMach78 = 0.78; % unitless Mach for cruise phases

%% MISSION TARGETS %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Mission.Target.Valu = [UnitConversionPkg.ConvLength(2500*0.35, "naut mi", "m"); UnitConversionPkg.ConvLength(2500*0.65, "naut mi", "m")]; % Final cruise target range
Mission.Target.Type = ["Dist";"Dist"];

%% MISSION SEGMENTS %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Mission.Segs = [ ...
    "Climb"; "Cruise"; "Climb"; "Cruise"; "Descent" ...
];

Mission.ID = [1; 1; 2; 2; 2]; % Single mission, no separate reserve yet

Mission.AltBeg = [ ...
    AltTko; ...
    AltCrs33; ...
    AltCrs33; ...
    AltCrs35; ...
    AltCrs35 ...
];

Mission.AltEnd = [ ...
    AltCrs33; ...
    AltCrs33; ...
    AltCrs35; ...
    AltCrs35; ...
    AltTko ...
];

Mission.VelBeg = [ ...
    0.2;...
    VelMach78; ...
    VelMach78; ...
    VelMach78; ...
    0.78 ...
];

Mission.VelEnd = [ ...
    VelMach78;...
    VelMach78; ...
    VelMach78; ...
    VelMach78; ...
    0.2 ...
];

Mission.TypeBeg = [ ...
    "Mach"; ...
    "Mach"; ...
    "Mach"; ...
    "Mach"; ...
    "Mach" ...
];

Mission.TypeEnd = Mission.TypeBeg;

Mission.ClbRate = [ ...
    NaN; ... % Climb phase uses altitude targets, no explicit rate
    NaN; ...
    NaN; ...
    NaN; ...
    NaN ...
];

%% RESERVE / POST MISSION (Placeholder) %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

% TODO: Add 45-min loiter at 10k ft + 100 nmi diversion (if required)

%% SAVE MISSION PROFILE %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

Aircraft.Mission.Profile = Mission;

end