% Optimize one fixed-aircraft 1000 nmi ERJ mission and compare with paper.

clearvars;
clc;

Input = load("ERJ175LR_current_Lam_10pctTko_30pctEMClimb.mat", "SizedAircraft");
Aircraft = Input.SizedAircraft;
Aircraft.Specs.Performance.Range = UnitConversionPkg.ConvLength(1000, "naut mi", "m");
Aircraft.Specs.Battery.BegSOC = 100;
Aircraft.Settings.Analysis.Type = -1;
Aircraft.Settings.PowerOptMaxIter = 100;

[OptAircraft, PCbest, OptimizerTime_min] = ...
    OptimizationPkg.MissionPowerOpt(Aircraft, ...
                                    @MissionProfilesPkg.ERJ_ClimbThenAccel);

MainSegs = find(OptAircraft.Mission.Profile.ID == 1);
MainEnd = OptAircraft.Mission.Profile.SegEnd(MainSegs(end));
Batt = find(OptAircraft.Specs.Propulsion.PropArch.SrcType == 0, 1);

MainMissionFuel_kg = OptAircraft.Mission.History.SI.Weight.Fburn(MainEnd);
FullProfileFuel_kg = OptAircraft.Mission.History.SI.Weight.Fburn(end);
MainMissionBatteryEnergy_kWh = ...
    OptAircraft.Mission.History.SI.Energy.E_ES(MainEnd, Batt) / 3.6e6;
FullProfileBatteryEnergy_kWh = ...
    OptAircraft.Mission.History.SI.Energy.E_ES(end, Batt) / 3.6e6;
BatteryCapacity_kWh = OptAircraft.Specs.Weight.Batt * 0.25;
ElectricMotorWeight_kg = sum(OptAircraft.Specs.Weight.EM, "all");
MinimumSOC_pct = min(OptAircraft.Mission.History.SI.Power.SOC(:, Batt));

PaperBlockFuel_kg = 9364;
PaperBatteryCapacity_kWh = 249.1;
SizedFuel_kg = Aircraft.Specs.Weight.Fuel;
ElectricMotorPower_kW = sum(Aircraft.Specs.Propulsion.SLSPower( ...
    Aircraft.Specs.Propulsion.PropArch.TrnType == 0)) / 1000;
PaperComparison = table( ...
    ["SizedFuel_kg"; "BatteryCapacity_kWh"; "ElectricMotorPower_kW"], ...
    [PaperBlockFuel_kg; PaperBatteryCapacity_kWh; 913.0], ...
    [SizedFuel_kg; BatteryCapacity_kWh; ElectricMotorPower_kW], ...
    100 .* ([SizedFuel_kg; BatteryCapacity_kWh; ElectricMotorPower_kW] - ...
    [PaperBlockFuel_kg; PaperBatteryCapacity_kWh; 913.0]) ./ ...
    [PaperBlockFuel_kg; PaperBatteryCapacity_kWh; 913.0], ...
    'VariableNames', {'Metric', 'Paper', 'CurrentBranch', 'DifferencePercent'});

RunMetadata = struct("Range_nmi", 1000, "InitialSOC_pct", 100, ...
    "AnalysisType", -1, "AircraftSizeFixed", true, ...
    "OptimizedSchedule", "LamDwn", ...
    "Profile", "MissionProfilesPkg.ERJ_ClimbThenAccel");

save("ERJ175LR_1000nmi_MissionPowerOpt_LamDwn.mat", "OptAircraft", ...
    "PCbest", "OptimizerTime_min", "MainMissionFuel_kg", ...
    "FullProfileFuel_kg", "MainMissionBatteryEnergy_kWh", ...
    "FullProfileBatteryEnergy_kWh", "BatteryCapacity_kWh", ...
    "SizedFuel_kg", "ElectricMotorPower_kW", "ElectricMotorWeight_kg", ...
    "MinimumSOC_pct", "PaperComparison", ...
    "RunMetadata", "-v7.3");

disp(PaperComparison);
fprintf("Main mission fuel: %.3f kg\n", MainMissionFuel_kg);
fprintf("Full profile fuel: %.3f kg\n", FullProfileFuel_kg);
fprintf("Main mission battery use: %.3f kWh\n", MainMissionBatteryEnergy_kWh);
fprintf("Full profile battery use: %.3f kWh\n", FullProfileBatteryEnergy_kWh);
fprintf("Minimum SOC: %.3f %%\n", MinimumSOC_pct);
fprintf("Electric motor weight: %.3f kg\n", ElectricMotorWeight_kg);
