% Optimize ERJ-175LR mission power splits with the current MissionPowerOpt.

clearvars;
clc;

InputFile = "ERJ175LR_current_Lam_10pctTko_30pctEMClimb.mat";
OutputFile = "ERJ175LR_MissionPowerOpt_LamDwn.mat";
PaperFuel_kg = 14697;
PaperBatteryEnergy_kWh = 635.3;

Input = load(InputFile, "SizedAircraft");
BaselineAircraft = Input.SizedAircraft;
BaselineAircraft.Settings.Analysis.MaxIter = 1;
BaselineAircraft.Settings.PowerOptMaxIter = 100;

[OptAircraft, PCbest, OptimizerTime_min] = ...
    OptimizationPkg.MissionPowerOpt(BaselineAircraft, ...
                                    @MissionProfilesPkg.ERJ_ClimbThenAccel);

OptimizedFuel_kg = OptAircraft.Mission.History.SI.Weight.Fburn(end);
BatteryWeight_kg = OptAircraft.Specs.Weight.Batt;
BatteryEnergy_kWh = BatteryWeight_kg * 0.25;
ElectricMotorWeight_kg = sum(OptAircraft.Specs.Weight.EM, "all");

PaperComparison = table( ...
    ["SingleMissionFuel_kg"; "BatteryEnergy_kWh"], ...
    [PaperFuel_kg; PaperBatteryEnergy_kWh], ...
    [OptimizedFuel_kg; BatteryEnergy_kWh], ...
    100 .* ([OptimizedFuel_kg; BatteryEnergy_kWh] - ...
            [PaperFuel_kg; PaperBatteryEnergy_kWh]) ./ ...
           [PaperFuel_kg; PaperBatteryEnergy_kWh], ...
    'VariableNames', {'Metric', 'Paper', 'CurrentBranch', 'DifferencePercent'});

RunMetadata = struct( ...
    "Branch", "emma_poweropt_update", ...
    "Profile", "MissionProfilesPkg.ERJ_ClimbThenAccel", ...
    "Optimizer", "OptimizationPkg.MissionPowerOpt", ...
    "OptimizedSchedule", "LamDwn", ...
    "MissionIterationsPerEvaluation", 1, ...
    "MaxSQPIterations", 100, ...
    "ConvergenceStatus", "optimizer-controlled", ...
    "InputFile", InputFile, ...
    "OptimizerTime_min", OptimizerTime_min, ...
    "ElectricMotorWeight_kg", ElectricMotorWeight_kg);

save(OutputFile, "OptAircraft", "PCbest", "OptimizerTime_min", ...
    "OptimizedFuel_kg", "BatteryWeight_kg", "BatteryEnergy_kWh", ...
    "ElectricMotorWeight_kg", "PaperComparison", "RunMetadata", "-v7.3");

disp(PaperComparison);
fprintf("Electric motor weight: %.3f kg\n", ElectricMotorWeight_kg);
fprintf("Saved %s\n", OutputFile);
