% Run SequencePowerOpt on the five-flight sequence used in the paper.

clearvars;
clc;
TotalRunTimer = tic;
RunStarted = datetime("now");

Input = load("ERJ175LR_current_Lam_10pctTko_30pctEMClimb.mat", "SizedAircraft");
SequenceData = load("Sequence.mat", "tables");
Aircraft = Input.SizedAircraft;
Sequence = SequenceData.tables{8};

Aircraft.Settings.Analysis.Type = -1;
Aircraft.Settings.PowerOptMaxIter = 200;
Aircraft.Settings.PowerOptMaxStarts = 3;
Aircraft.Specs.Battery.Charging = 150e3;

[OptimizedAircraft, PCbest, OptimizerTime_min, OptSeqTable, ...
    ExitFlag, OptimizerOutput] = ...
    OptimizationPkg.SequencePowerOpt(Aircraft, Sequence);

nflight = height(Sequence);
Fuel_kg = zeros(nflight, 1);
BatteryEnergy_kWh = zeros(nflight, 1);
InitialSOC_pct = zeros(nflight, 1);
FinalSOC_pct = zeros(nflight, 1);
FullFuel_kg = zeros(nflight, 1);
FullBatteryEnergy_kWh = zeros(nflight, 1);
TakeoffWeight_kg = zeros(nflight, 1);
DesignMTOW_kg = repmat(Aircraft.Specs.Weight.MTOW, nflight, 1);
MinimumPowerMargin_W = zeros(nflight, 1);

for iflight = 1:nflight
    A = OptimizedAircraft.(sprintf("Aircraft%d", iflight));
    MainSegs = find(A.Mission.Profile.ID == 1);
    MainEnd = A.Mission.Profile.SegEnd(MainSegs(end));
    Batt = find(A.Specs.Propulsion.PropArch.SrcType == 0, 1);
    Fuel_kg(iflight) = A.Mission.History.SI.Weight.Fburn(MainEnd);
    BatteryEnergy_kWh(iflight) = ...
        A.Mission.History.SI.Energy.E_ES(MainEnd, Batt) / 3.6e6;
    InitialSOC_pct(iflight) = A.Mission.History.SI.Power.SOC(1, Batt);
    FinalSOC_pct(iflight) = A.Mission.History.SI.Power.SOC(MainEnd, Batt);
    FullFuel_kg(iflight) = A.Mission.History.SI.Weight.Fburn(end);
    FullBatteryEnergy_kWh(iflight) = ...
        A.Mission.History.SI.Energy.E_ES(end, Batt) / 3.6e6;
    TakeoffWeight_kg(iflight) = A.Mission.History.SI.Weight.CurWeight(1);
    PowerMargin = A.Mission.History.SI.Power.Pav - ...
        A.Mission.History.SI.Power.Preq;
    MinimumPowerMargin_W(iflight) = min(PowerMargin, [], "all", "omitnan");
end

TotalFuel_kg = sum(Fuel_kg);
TotalBatteryEnergy_kWh = sum(BatteryEnergy_kWh);
TotalFullFuel_kg = sum(FullFuel_kg);
TotalFullBatteryEnergy_kWh = sum(FullBatteryEnergy_kWh);
ElectricMotorWeight_kg = sum(Aircraft.Specs.Weight.EM, "all");
TotalRunTime_min = toc(TotalRunTimer) / 60;

FlightResults = table((1:nflight)', Sequence.DISTANCE, ...
    Sequence.GROUND_TIME, Fuel_kg, BatteryEnergy_kWh, ...
    InitialSOC_pct, FinalSOC_pct, TakeoffWeight_kg, DesignMTOW_kg, ...
    MinimumPowerMargin_W, ...
    'VariableNames', {'Flight', 'Distance_nmi', 'GroundTime_min', ...
    'Fuel_kg', 'BatteryEnergy_kWh', 'InitialSOC_pct', 'FinalSOC_pct', ...
    'TakeoffWeight_kg', 'DesignMTOW_kg', 'MinimumPowerMargin_W'});

FullProfileResults = table((1:nflight)', Sequence.DISTANCE, ...
    Sequence.GROUND_TIME, FullFuel_kg, FullBatteryEnergy_kWh, ...
    'VariableNames', {'Flight', 'Distance_nmi', 'GroundTime_min', ...
    'FullFuel_kg', 'FullBatteryEnergy_kWh'});

PaperFuel_kg = 14673.742;
PaperBatteryEnergy_kWh = 635.553;
PaperComparison = table( ...
    ["TotalFuel_kg"; "TotalBatteryEnergy_kWh"], ...
    [PaperFuel_kg; PaperBatteryEnergy_kWh], ...
    [TotalFuel_kg; TotalBatteryEnergy_kWh], ...
    100 .* ([TotalFuel_kg; TotalBatteryEnergy_kWh] - ...
    [PaperFuel_kg; PaperBatteryEnergy_kWh]) ./ ...
    [PaperFuel_kg; PaperBatteryEnergy_kWh], ...
    'VariableNames', {'Metric', 'Paper', 'CurrentBranch', 'DifferencePercent'});

PaperFullComparison = table( ...
    ["TotalFullFuel_kg"; "TotalFullBatteryEnergy_kWh"], ...
    [PaperFuel_kg; PaperBatteryEnergy_kWh], ...
    [TotalFullFuel_kg; TotalFullBatteryEnergy_kWh], ...
    100 .* ([TotalFullFuel_kg; TotalFullBatteryEnergy_kWh] - ...
    [PaperFuel_kg; PaperBatteryEnergy_kWh]) ./ ...
    [PaperFuel_kg; PaperBatteryEnergy_kWh], ...
    'VariableNames', {'Metric', 'Paper', 'CurrentBranch', 'DifferencePercent'});

RunMetadata = struct("SequenceIndex", 8, "AnalysisType", -1, ...
    "AircraftSizeFixed", true, "MaxIterations", 200, ...
    "MaxStarts", 3, "ExitFlag", ExitFlag, ...
    "Iterations", OptimizerOutput.iterations, ...
    "StartAttempt", OptimizerOutput.StartAttempt, ...
    "RunStarted", string(RunStarted), ...
    "OptimizerTime_min", OptimizerTime_min, ...
    "TotalRunTime_min", TotalRunTime_min, ...
    "ChargerPower_kW", 150, ...
    "ChargingRule", "GROUND_TIME(next flight) - 7 minutes", ...
    "GateTimes_min", Sequence.GROUND_TIME.', ...
    "Objective", "Total main-mission fuel burn", ...
    "OptimizedSchedule", "LamDwn");

save("ERJ175LR_SequencePowerOpt_Fuel_LamDwn_150kW.mat", "OptimizedAircraft", ...
    "PCbest", "OptimizerTime_min", "OptSeqTable", "Sequence", ...
    "FlightResults", "FullProfileResults", ...
    "TotalFuel_kg", "TotalBatteryEnergy_kWh", ...
    "TotalFullFuel_kg", "TotalFullBatteryEnergy_kWh", ...
    "ElectricMotorWeight_kg", "PaperComparison", ...
    "PaperFullComparison", "RunMetadata", "ExitFlag", ...
    "OptimizerOutput", "TotalRunTime_min", "RunStarted", "-v7.3");

disp(FlightResults);
disp(PaperComparison);
disp(PaperFullComparison);
fprintf("Electric motor weight: %.3f kg\n", ElectricMotorWeight_kg);
fprintf("Converged in %d iterations on start %d (exit flag %d).\n", ...
    OptimizerOutput.iterations, OptimizerOutput.StartAttempt, ExitFlag);
fprintf("Optimizer runtime: %.3f min; total runtime: %.3f min.\n", ...
    OptimizerTime_min, TotalRunTime_min);
