% Compare the independent-mission and sequence optimizers on flight 1 of
% Sequence 8 using the same fixed-size ERJ17LR PHE aircraft.

clearvars;
clc;
RunTimer = tic;

if isfile(fullfile("output", "ERJ17LR_PHE_sized.mat"))
    Input = load(fullfile("output", "ERJ17LR_PHE_sized.mat"), "SizedPHE");
    BaseAircraft = Input.SizedPHE;
    InputFile = fullfile("output", "ERJ17LR_PHE_sized.mat");
else
    Input = load(fullfile("output", "ERJ17LR_PHE_sized_cycle_fixed.mat"), "A");
    BaseAircraft = Input.A;
    InputFile = fullfile("output", "ERJ17LR_PHE_sized_cycle_fixed.mat");
end

SequenceData = load("Sequence.mat", "tables");
FirstFlight = SequenceData.tables{8}(1, :);

speed = convvel(FirstFlight.SPEED_mph, "mph", "m/s");
MissionAircraft = BaseAircraft;
MissionAircraft.Specs.Performance.Range = UnitConversionPkg.ConvLength( ...
    FirstFlight.DISTANCE, "naut mi", "m");
[~, ~, MissionAircraft.Specs.Performance.Vels.Crs] = ...
    MissionSegsPkg.ComputeFltCon(FirstFlight.ALTITUDE_m, 0, "TAS", speed);
MissionAircraft.Specs.Performance.Alts.Crs = FirstFlight.ALTITUDE_m;
MissionAircraft.Specs.Weight.Payload = convmass( ...
    FirstFlight.PAYLOAD_lb, "lbm", "kg");
MissionAircraft.Specs.Power.Battery.BegSOC = 100;
MissionAircraft.Specs.Battery.Charging = 150e3;
MissionAircraft.Settings.Analysis.Type = -1;
MissionAircraft.Settings.PowerOptMaxIter = 500;

[MissionAircraft, MissionPC, MissionOptimizerTime_min, ...
    MissionExitFlag, MissionOptimizerOutput] = ...
    OptimizationPkg.MissionPowerOpt(MissionAircraft, ...
    @MissionProfilesPkg.ERJ_ClimbThenAccel);

MainSegs = find(MissionAircraft.Mission.Profile.ID == 1);
MissionMainEnd = MissionAircraft.Mission.Profile.SegEnd(MainSegs(end));
Batt = find(MissionAircraft.Specs.Propulsion.PropArch.SrcType == 0, 1);
MissionFuel_kg = MissionAircraft.Mission.History.SI.Weight.Fburn(MissionMainEnd);
MissionFinalSOC_pct = MissionAircraft.Mission.History.SI.Power.SOC(MissionMainEnd, Batt);
MissionEnergy_kWh = MissionAircraft.Mission.History.SI.Energy.E_ES(MissionMainEnd, Batt) / 3.6e6;
MissionPowerExcess_W = MissionAircraft.Mission.History.SI.Power.Preq - ...
    MissionAircraft.Mission.History.SI.Power.Pav;
MissionPowerExcess_W(~isfinite(MissionPowerExcess_W)) = 0;
MissionMaxPowerExcess_W = max(MissionPowerExcess_W, [], "all");

SequenceAircraft = BaseAircraft;
SequenceAircraft.Specs.Power.Battery.BegSOC = 100;
SequenceAircraft.Specs.Battery.Charging = 150e3;
SequenceAircraft.Settings.Analysis.Type = -1;
SequenceAircraft.Settings.PowerOptMaxIter = 500;
SequenceAircraft.Settings.PowerOptMaxStarts = 3;
[SequenceAircraftByFlight, SequencePC, SequenceOptimizerTime_min, ...
    SequenceTable, SequenceExitFlag, SequenceOptimizerOutput] = ...
    OptimizationPkg.SequencePowerOpt(SequenceAircraft, FirstFlight);

SequenceAircraft = SequenceAircraftByFlight.Aircraft1;
MainSegs = find(SequenceAircraft.Mission.Profile.ID == 1);
SequenceMainEnd = SequenceAircraft.Mission.Profile.SegEnd(MainSegs(end));
Batt = find(SequenceAircraft.Specs.Propulsion.PropArch.SrcType == 0, 1);
SequenceFuel_kg = SequenceAircraft.Mission.History.SI.Weight.Fburn(SequenceMainEnd);
SequenceFinalSOC_pct = SequenceAircraft.Mission.History.SI.Power.SOC(SequenceMainEnd, Batt);
SequenceEnergy_kWh = SequenceAircraft.Mission.History.SI.Energy.E_ES(SequenceMainEnd, Batt) / 3.6e6;
SequencePowerExcess_W = SequenceAircraft.Mission.History.SI.Power.Preq - ...
    SequenceAircraft.Mission.History.SI.Power.Pav;
SequencePowerExcess_W(~isfinite(SequencePowerExcess_W)) = 0;
SequenceMaxPowerExcess_W = max(SequencePowerExcess_W, [], "all");

Conventional = load(fullfile("output", ...
    "ERJ175LR_Conventional_Sequence8_MainMission.mat"), "FlightResults");
ConventionalFuel_kg = Conventional.FlightResults.ConventionalMainFuel_kg(1);

FuelDifference_kg = MissionFuel_kg - SequenceFuel_kg;
FuelDifference_pct = 100 * FuelDifference_kg / SequenceFuel_kg;
MissionReductionVsConventional_pct = ...
    100 * (ConventionalFuel_kg - MissionFuel_kg) / ConventionalFuel_kg;
SequenceReductionVsConventional_pct = ...
    100 * (ConventionalFuel_kg - SequenceFuel_kg) / ConventionalFuel_kg;

Comparison = table( ...
    ["Independent mission"; "One-flight sequence"; "Conventional"], ...
    [MissionFuel_kg; SequenceFuel_kg; ConventionalFuel_kg], ...
    [MissionFinalSOC_pct; SequenceFinalSOC_pct; NaN], ...
    [MissionEnergy_kWh; SequenceEnergy_kWh; NaN], ...
    [MissionMaxPowerExcess_W; SequenceMaxPowerExcess_W; NaN], ...
    'VariableNames', {'Method', 'MainMissionFuel_kg', ...
    'FinalSOC_pct', 'BatteryEnergy_kWh', 'MaxPowerExcess_W'});

TotalRunTime_min = toc(RunTimer) / 60;
RunMetadata = struct("SequenceIndex", 8, "Flight", 1, ...
    "InputFile", InputFile, "AnalysisType", -1, ...
    "MissionOptimizerMaxIterations", 500, ...
    "SequenceOptimizerMaxIterations", 500, ...
    "ChargerPower_kW", 150, "FullMissionPowerConstraint", true, ...
    "ObjectiveBoundary", "End of main mission (Mission.Profile.ID == 1)");

save(fullfile("output", "ERJ17LR_PHE_Sequence8_FirstMission_FullPowerComparison.mat"), ...
    "BaseAircraft", "FirstFlight", "MissionAircraft", "MissionPC", ...
    "MissionOptimizerTime_min", "MissionExitFlag", "MissionOptimizerOutput", ...
    "MissionFuel_kg", "MissionFinalSOC_pct", "MissionMaxPowerExcess_W", ...
    "MissionEnergy_kWh", "SequenceAircraftByFlight", "SequencePC", ...
    "SequenceOptimizerTime_min", "SequenceTable", "SequenceExitFlag", ...
    "SequenceOptimizerOutput", "SequenceFuel_kg", "SequenceFinalSOC_pct", ...
    "SequenceEnergy_kWh", "SequenceMaxPowerExcess_W", ...
    "ConventionalFuel_kg", "FuelDifference_kg", ...
    "FuelDifference_pct", "MissionReductionVsConventional_pct", ...
    "SequenceReductionVsConventional_pct", "Comparison", "RunMetadata", ...
    "TotalRunTime_min", "-v7.3");

disp(Comparison);
fprintf("Independent minus sequence: %.6f kg (%+.6f%%)\n", ...
    FuelDifference_kg, FuelDifference_pct);
fprintf("Conventional reduction: independent %.6f%%; sequence %.6f%%\n", ...
    MissionReductionVsConventional_pct, SequenceReductionVsConventional_pct);
fprintf("Sequence exit flag %d after %d iterations.\n", ...
    SequenceExitFlag, SequenceOptimizerOutput.iterations);
fprintf("Mission exit flag %d after %d iterations.\n", ...
    MissionExitFlag, MissionOptimizerOutput.iterations);
fprintf("Total runtime: %.3f min\n", TotalRunTime_min);
