function [Power] = SplitPower(Aircraft, Preq, LamTS, LamTSPS, LamPSPS)
%
% [Power] = SplitPower(Aircraft, Preq, LamTS, LamTSPS, LamPSPS)
% written by Paul Mokotoff, prmoko@umich.edu
% last updated: 08 mar 2024
%
% Split the total thrust/power to find the power produced by each component
% in the powertrain.
%
% INPUTS:
%     Aircraft - structure with information about the aircraft,
%                specifically information about the efficiciencies in the
%                powertrain.
%                size/type/units: 1-by-1 / struct / []
%
%     Preq     - required power as a function of time.
%                size/type/units: n-by-1 / double / [W]
%
%     LamTS    - split between thrust sources.
%                size/type/units: 1-by-nts / double / []
%
%     LamTSPS  - split between thrust-power sources.
%                size/type/units: nts-by-nps / double / []
%
%     LamPSPS  - split between power-power sources.
%                size/type/units: nps-by-nps / double / []
%
% OUTPUTS:
%     Power    - power generated by each power source.
%                size/type/units: n-by-nps
%


%% PRE-PROCESSING %%
%%%%%%%%%%%%%%%%%%%%

% get the efficiencies
EtaTSPS = Aircraft.Specs.Propulsion.Eta.TSPS;
EtaPSPS = Aircraft.Specs.Propulsion.Eta.PSPS;


%% THRUST/POWER PROPAGATION %%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
% split the power amongst the thrust sources
PowerTS = Preq * LamTS;

% split the power amongst the power  sources (both driving and driven)
Power   = PowerTS * (LamTSPS ./ EtaTSPS) ...
                  * (LamPSPS ./ EtaPSPS) ;

% ----------------------------------------------------------

end