name: Draft PDF
on:
  push:
    paths:
      - JOSS-Paper/*
      - .github/workflows/draft-pdf.yml

jobs:
  paper:
    runs-on: ubuntu-latest
    name: Paper Draft
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build draft PDF
        uses: openjournals/openjournals-draft-action@master
      - name: Open Journals PDF Generator
        uses: openjournals/openjournals-draft-action@v.1.0    
        with:
          journal: joss
          paper-path: JOSS-Paper/paper.md
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: paper
          path: JOSS-Paper/paper.pdf
      - name: Commit PDF to repository
        uses: EndBug/add-and-commit@v9
        with:
          message: '(auto) Paper PDF Draft'
          add: 'JOSS-Paper/paper.pdf'